# Generated by Django 5.1.1 on 2024-10-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dutchmunicipality',
            old_name='geom',
            new_name='geometry',
        ),
        migrations.RenameField(
            model_name='park',
            old_name='geom',
            new_name='geometry',
        ),
    ]
